require: rubocop-rails

AllCops:
  Exclude:
    - '.pryrc'
    - 'bin/*'
    - 'spec/spec_helper.rb'
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Exclude:

Lint/EmptyBlock:
  Exclude:
    - db/schema.rb
